site_name: Gluu Cluster Docs
site_description: Documenation for the Gluu Server Cluster
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs-cluster
theme: spacelab

theme_dir: ./theme/mkdocs/
theme_center_lead: false
include_search: true

pages:

# Home Page
- [index.md, Home]

# Admin Guide Sections
- [admin-guide/overview/index.md, Admin Guide, Overview]
- [admin-guide/getting-started/index.md, Admin Guide, Getting Started]
- [admin-guide/installation/index.md, Admin Guide, Installation]
- [admin-guide/cluster-management/index.md, Admin Guide, Cluster Management]
- [admin-guide/components/index.md, Admin Guide, Components]
# - [admin-guide/monitoring/index.md, Admin Guide, Monitoring]
#- [admin-guide/testing/index.md, Admin Guide, Testing]
#- [admin-guide/tuning/index.md, Admin Guide, Tuning]
- [admin-guide/webui/index.md, Admin Guide, Web Interface]
- [admin-guide/troubleshooting/index.md, Admin Guide, Troubleshooting]
- [admin-guide/recovery/index.md, Admin Guide, Recovery]
- [admin-guide/migration/index.md, Admin Guide, Migration]

# API section
- [reference/api/index.md, Reference, API]

# Sub Pages of Reference / API
- [reference/api/cluster.md, hidden]
- [reference/api/provider.md, hidden]
- [reference/api/node.md, hidden]
- [reference/api/license_key.md, hidden]

# Articles Sections
