site_name: Gluu Cluster Docs
site_description: Documenation for the Gluu Server Cluster
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs-cluster
theme: spacelab

theme_dir: ./theme/mkdocs/
theme_center_lead: false
include_search: true

pages:

# Home Page
- ['index.md', 'Home']

# Admin Guide Sections
- ['docs/admin-guide/overview/index.md', 'Admin Guide', 'Overview']
- ['docs/admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['docs/admin-guide/components/index.md', 'Admin Guide', 'Components']
- ['docs/admin-guide/monitoring/index.md', 'Admin Guide', 'Monitoring']
- ['docs/admin-guide/testing/index.md', 'Admin Guide', 'Testing']
- ['docs/admin-guide/tuning/index.md', 'Admin Guide', 'Tuning']

# Sub Pages of Admin Guide / Installation
- ['docs/admin-guide/installation/package.md', '**HIDDEN**']

# API section
- ['docs/reference/api/index.md', 'Reference', 'API']

# Sub Pages of Reference / API
- ['docs/reference/api/provider.md', '**HIDDEN**']
- ['docs/reference/api/cluster.md', '**HIDDEN**']
- ['docs/reference/api/node.md', '**HIDDEN**']
